version: '3.8'

services:
  frontend:
    build: .
    container_name: lazydrobe-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - lazydrobe-network

networks:
  lazydrobe-network:
    driver: bridge
